name: CI/CD + Security Scan - Project 1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'          # This helps with faster and stable installs

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --no-cache-dir